Algoritmo "atividadetabuada9"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/05/2023
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Eu sei matemática")
escreval("Tabuada do 9")
escreval("94 x 1 =", 94*1)
escreval("94 x 2 =", 94*2)
escreval("94 x 3 =", 94*3)
escreval("94 x 4 =", 94*4)
escreval("94 x 5 =", 94*5)
escreval("94 x 6 =", 94*6)
escreval("94 x 7 =", 94*7)
escreval("94 x 8 =", 94*8)
escreval("94 x 9 =", 94*9)
Fimalgoritmo