Algoritmo "atividadedocirculo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 18/05/2023
Var
// Seção de Declarações das variáveis
raio,area: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Por favor digite um raio: ")
leia(raio)
area <- raio^2 * pi
escreval("O valor da área do circulo é: ", area)
escreva("O valor do diâmetro é: ",raio*2)
Fimalgoritmo