Algoritmo "calculoscomabcd"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/05/2023
Var
// Seção de Declarações das variáveis 
a,b,c,d:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite o valor de A: ")
leia(a)
escreva("Digite o valor de B: ")
leia(b)
escreva("Digite o valor de C: ")
leia(c)
escreva("Digite o valor de D: ")
leia(d)
escreval("O valor de A x B é: ",a*b)
escreval("O valor de A + B é: ",a+b)
escreval("O valor de A x C é: ",a*c)
escreval("O valor de A + C é: ",a+c)
escreval("O valor de A x D é: ",a*d)
escreval("O valor de A + D é: ",a+d)
escreval("O valor de B x C é: ",b*c)
escreval("O valor de B + C é: ",b+c)
escreval("O valor de B x D é: ",b*d)
escreval("O valor de B + D é: ",b+d)
escreval("O valor de C x D é: ",c*d)
escreval("O valor de C + D é: ",c+d)
Fimalgoritmo