Algoritmo "calculodeareadotriangulo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/05/2023
Var
// Seção de Declarações das variáveis 
area,base,altura: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Insira a altura do triângulo: ")
leia(altura)
escreval("Insira a base do triângulo: ")
leia(base)
area <- (base*altura)/2
escreva("A área do triângulo é: ",area)

Fimalgoritmo