Algoritmo "Calculadora"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 18/05/2023
Var
// Seção de Declarações das variáveis 
numero1, numero2, soma, multiplica: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Por favor digite o 1° número:")
leia(numero1)
escreva("Por favor digite o 2° número:")
leia(numero2)
soma <- numero1 + numero2
multiplica <- numero1 * numero2
escreval("O resultado da soma é:",soma)
escreval("O resultado da multiplicação é:", multiplica)









Fimalgoritmo