Algoritmo "conversaodetemperatura2"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/05/2023
Var
// Seção de Declarações das variáveis
f,c:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Insira a temperatura em graus Fahrenheit: ")
leia(f)
c <- (f-32)*(5/9)
escreva("A temperatura equivalente em graus Celcius é: ", c)
Fimalgoritmo