Algoritmo "nomecompleto"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/05/2023
Var
// Seção de Declarações das variáveis 
nome,sobrenome,nomecompleto: caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite o seu nome: ")
leia(nome)
escreva("Digite o seu sobrenome: ")
leia(sobrenome)
nomecompleto <- nome+" "+sobrenome
escreva("O seu nome completo é ",nomecompleto)

Fimalgoritmo