Algoritmo "somadeinteiros"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/05/2023
Var
// Seção de Declarações das variáveis 
n1,n2,resultado: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Apresente um número: ")
leia(n1)
escreva("Apresente mais um número: ")
leia(n2)
resultado <- n1+n2
escreva("A soma dos dois números é: ", resultado)

Fimalgoritmo