Algoritmo "trocadevalores"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/05/2023
Var
// Seção de Declarações das variáveis 
a,b,c:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("insira o valor de A: ")
leia(a)
escreva("insira o valor de B: ")
leia(b)
c <- a
a <- b
b <- c
escreval("o novo valor de A é",a)
escreval("o novo valor de B é",b)

Fimalgoritmo