Algoritmo "volumedalatadeoleo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/05/2023
Var
// Seção de Declarações das variáveis 
raio,altura,volume: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Insira o valor do raio: ")
leia(raio)
escreva("Insira o valor da altura: ")
leia(altura)
volume <- pi*raio^2*altura
escreva("O volume da lata de óleo é de: ",volume)
Fimalgoritmo