Algoritmo "conta10"
// PROGRAMAÇÃO  DE  SOLUÇÕES  COMPUTACIONAIS   OU  ALGORITIMOS  E  PROGRAMAÇÃO
// Rodrigo Gomes Lobo de Faria 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : João Pedro Bastos Neves
// Data atual  : 30/03/2026
Var

numInicio, numFim, contador : inteiro


Inicio

numInicio <- 1
numFIm <- 10

para contador de numInicio ate numFim faca

escreval(contador)

fimpara

Fimalgoritmo